FROM node:24-alpine3.23

WORKDIR /app

ENV NODE_ENV=development
ENV PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

COPY ./package*.json ./

RUN npm ci

COPY ./ ./

EXPOSE 3000

CMD ["npm", "run", "dev"]